# Generated by Django 4.0.5 on 2022-06-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tape_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tape',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
